# This file is used to create
#	MSVC Win32 Executable files and Shared Libraries

CC = cl
AR = lib
LD = link

# Optimize
# Do not use /sdl, or the CRT functions will be called DEPRECATED
CFLAGS = /EHsc /Gd /c /O2 /fp:precise /std:c++14 /WX /sdl
WFLAGS = /D_CRT_SECURE_NO_WARNINGS
LDFLAGS = /DLL /VERSION:0.1
LEFLAGS = /SUBSYSTEM:CONSOLE /VERSION:0.1
UTILDIR = .\utils
LIBDIR = .\lib
OBJDIR = .\obj
EXEDIR = .\exe

SHARELIB = KF4Win.dll
IMPLIB = KF4Win.lib
STATICLIB = KissFft4Win.lib

SRCFILE = kiss_fft_4win.cpp kiss_fft.cpp kiss_fft_4win_block.cpp kiss_fft_4win_cstyle_api.cpp
LIBOBJ  = kiss_fft_4win.obj kiss_fft.obj kiss_fft_4win_block.obj kiss_fft_4win_cstyle_api.obj

######################################################
# 			 Do not change the data below,			 #
#		unless you know what you are doing now.		 #
######################################################


all: setenv GetWavData.exe $(SHARELIB) $(IMPLIB) finalize

# Targets
$(SHARELIB): KF4Win.obj
	$(LD) $(LDFLAGS) /IMPLIB:$(IMPLIB) $(LIBOBJ) /out:$(LIBDIR)\$@

$(STATICLIB): KF4Win.obj
	$(AR) $(LIBOBJ) /out:$(LIBDIR)\$@

KF4Win.obj:
	$(CC) $(CFLAGS) $(SRCFILE)


# Utilities
GetWavData.exe: GetWavData.obj
	$(LD) $(LEFLAGS) GetWavData.obj /out:$(EXEDIR)\$@

GetWavData.obj:
	$(CC) $(CFLAGS) $(WFLAGS) $(UTILDIR)\GetWavData.cpp

setenv:
	if not exist $(LIBDIR) mkdir $(LIBDIR)
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	if not exist $(EXEDIR) mkdir $(EXEDIR)

finalize:
	move *.obj $(OBJDIR)
	move *.exp $(LIBDIR)
	move *.lib $(LIBDIR)

clean:
	-del /f /q $(LIBDIR)
	-del /f /q $(OBJDIR)
	-del /f /q $(EXEDIR)
	rmdir /S /Q $(LIBDIR)
	rmdir /S /Q $(OBJDIR)
	rmdir /S /Q $(EXEDIR)
